require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DiscountsController do
login_user
  # This should return the minimal set of attributes required to create a valid
  # Discount. As you add validations to Discount, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "amount" => "1"  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiscountsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all discounts as @discounts" do
      discount = create(:discount)
      get :index, {}
      assigns(:discounts).should eq([discount])
    end
  end

  describe "GET show" do
    it "assigns the requested discount as @discount" do
      discount = create(:discount)
      get :show, {:id => discount.to_param}
      assigns(:discount).should eq(discount)
    end
  end

  describe "GET new" do
    it "assigns a new discount as @discount" do
      get :new, {}
      assigns(:discount).should be_a_new(Discount)
    end
  end

  describe "GET edit" do
    it "assigns the requested discount as @discount" do
      discount = create(:discount)
      get :edit, {:id => discount.to_param}
      assigns(:discount).should eq(discount)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Discount" do
        expect {
          post :create, {:discount => valid_attributes}
        }.to change(Discount, :count).by(1)
      end

      it "assigns a newly created discount as @discount" do
        post :create, {:discount => valid_attributes}
        assigns(:discount).should be_a(Discount)
        assigns(:discount).should be_persisted
      end

      it "redirects to the created discount" do
        post :create, {:discount => valid_attributes}
        response.should redirect_to(root_path)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved discount as @discount" do
        # Trigger the behavior that occurs when invalid params are submitted
        Discount.any_instance.stub(:save).and_return(false)
        post :create, {:discount => { "amount" => "invalid value" }}
        assigns(:discount).should be_a_new(Discount)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Discount.any_instance.stub(:save).and_return(false)
        post :create, {:discount => { "amount" => "invalid value" }}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested discount" do
        discount = create(:discount)
        # Assuming there are no other discounts in the database, this
        # specifies that the Discount created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Discount.any_instance.should_receive(:update).with({ "amount" => "2" })
        put :update, {:id => discount.to_param, :discount => { "amount" => "2" }}
      end

      it "assigns the requested discount as @discount" do
        discount = create(:discount)
        put :update, {:id => discount.to_param, :discount => valid_attributes}
        assigns(:discount).should eq(discount)
      end

      it "redirects to the discount" do
        discount = create(:discount)
        put :update, {:id => discount.to_param, :discount => valid_attributes}
        response.should redirect_to(discount)
      end
    end

    describe "with invalid params" do
      it "assigns the discount as @discount" do
        discount = create(:discount)
        # Trigger the behavior that occurs when invalid params are submitted
        Discount.any_instance.stub(:save).and_return(false)
        put :update, {:id => discount.to_param, :discount => { "amount" => "invalid value" }}
        assigns(:discount).should eq(discount)
      end

      it "re-renders the 'edit' template" do
        discount = create(:discount)
        # Trigger the behavior that occurs when invalid params are submitted
        Discount.any_instance.stub(:save).and_return(false)
        put :update, {:id => discount.to_param, :discount => { "amount" => "invalid value" }}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested discount" do
      discount = create(:discount)
      expect {
        delete :destroy, {:id => discount.to_param}
      }.to change(Discount, :count).by(-1)
    end

    it "redirects to the discounts list" do
      discount = create(:discount)
      delete :destroy, {:id => discount.to_param}
      response.should redirect_to(discounts_url)
    end
  end

end
